### ISSUE TITLE
https://probes.telemetry.mozilla.org/ does not load

### ISSUE THREAD

**Issue by Trikolon** [georgf/fx-data-explorer#129]
https://probes.telemetry.mozilla.org/ does not load properly, it only shows the loading state spinner:
![image](https://user-images.githubusercontent.com/1077860/199541734-901ec2a6-9996-415c-8417-0ab18da0f94a.png)

In the devtools I can see an error about CORS:
```
probes.telemetry.mozilla.org/:1 Access to XMLHttpRequest at 'https://probeinfo.telemetry.mozilla.org/firefox/general' from origin 'https://probes.telemetry.mozilla.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
probeinfo.telemetry.mozilla.org/firefox/general:1          Failed to load resource: net::ERR_FAILED
createError.js:16 Uncaught (in promise) Error: Network Error
    at e.exports (createError.js:16:15)
    at p.onerror (xhr.js:83:14)
```
Looks like the failed network requests causes the script to fail.

Tested on:
macOS 12.1
Firefox Nightly
Firefox Stable
Chrome Stable
Safari Stable
German origin IP address

**Comment by rafrombrc** [comment]
The linked Data SRE fix seems to have resolved this issue, shift-reload might be needed to clear local cache.
